package doctor

import (
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
)

// TrackedIgnoredBeadsBackupCheck detects .beads/backup/*.jsonl files that are
// tracked in git despite being covered by a .gitignore rule.
//
// Root cause: bd's auto-export git-add side effect committed the backup JSONL
// files into repo history BEFORE the '.beads/backup/' ignore rule existed.
// .gitignore never untracks already-tracked files, so the stale copies linger
// in the index. When the gt runtime regenerates the backup dir during
// session-cycling, the old tracked copies are deleted on disk and surface as
// 'deleted:' noise in 'git status' for every crew/mayor workspace.
//
// This is warn-only: the remediation ('git rm --cached') requires a commit to
// be meaningful, and doctor must not commit across rig clones (merge queue) or
// polecat worktrees (MR pollution). The check surfaces the exact command so an
// operator can untrack per-repo. (gu-x6e7v)
type TrackedIgnoredBeadsBackupCheck struct {
	BaseCheck
}

// NewTrackedIgnoredBeadsBackupCheck creates a new tracked-ignored beads backup check.
func NewTrackedIgnoredBeadsBackupCheck() *TrackedIgnoredBeadsBackupCheck {
	return &TrackedIgnoredBeadsBackupCheck{
		BaseCheck: BaseCheck{
			CheckName:        "tracked-ignored-beads-backup",
			CheckDescription: "Detect git-tracked .beads/backup/ files that .gitignore should exclude",
			CheckCategory:    CategoryCleanup,
		},
	}
}

// Run scans every rig worktree for tracked-but-ignored .beads/backup/ files.
func (c *TrackedIgnoredBeadsBackupCheck) Run(ctx *CheckContext) *CheckResult {
	rigDirs, err := findRigDirs(ctx.TownRoot)
	if err != nil {
		return &CheckResult{
			Name:    c.Name(),
			Status:  StatusWarning,
			Message: fmt.Sprintf("Could not scan rigs: %v", err),
		}
	}

	// Collect distinct worktree roots from the .beads locations each rig exposes.
	// The parent of a .beads dir is the git working tree to probe.
	seen := make(map[string]bool)
	var worktreeRoots []string
	for _, rigDir := range rigDirs {
		for _, beadsDir := range getBeadsDirsToCheck(rigDir) {
			root := filepath.Dir(beadsDir)
			if !seen[root] {
				seen[root] = true
				worktreeRoots = append(worktreeRoots, root)
			}
		}
	}

	var details []string
	for _, root := range worktreeRoots {
		tracked := trackedIgnoredBackupFiles(root)
		if len(tracked) == 0 {
			continue
		}
		relRoot, relErr := filepath.Rel(ctx.TownRoot, root)
		if relErr != nil || relRoot == "" {
			relRoot = root
		}
		details = append(details, fmt.Sprintf("%s: %d tracked .beads/backup/ file(s) (run: git -C %s rm --cached -r .beads/backup/)",
			relRoot, len(tracked), relRoot))
	}

	if len(details) == 0 {
		return &CheckResult{
			Name:    c.Name(),
			Status:  StatusOK,
			Message: "No tracked-but-ignored .beads/backup/ files found",
		}
	}

	return &CheckResult{
		Name:    c.Name(),
		Status:  StatusWarning,
		Message: fmt.Sprintf("%d worktree(s) track ignored .beads/backup/ files", len(details)),
		Details: details,
		FixHint: "Untrack per-repo with 'git rm --cached -r .beads/backup/' then commit; the files stay on disk (regenerated by bd).",
	}
}

// trackedIgnoredBackupFiles returns the .beads/backup/ files that are both
// tracked in the index and matched by a .gitignore rule in the given worktree.
// Returns nil when the directory is not a git repo or has no such files.
func trackedIgnoredBackupFiles(worktreeRoot string) []string {
	// Confirm this is a git repo before probing the index.
	probe := exec.Command("git", "-C", worktreeRoot, "rev-parse", "--git-dir")
	if probe.Run() != nil {
		return nil
	}

	// --cached --ignored --exclude-standard lists index entries that match a
	// gitignore rule, i.e. tracked-but-ignored. Scope to .beads/backup/ so
	// intentionally-tracked .beads files (config.yaml, PRIME.md) are not flagged.
	cmd := exec.Command("git", "-C", worktreeRoot,
		"ls-files", "--cached", "--ignored", "--exclude-standard", "--", ".beads/backup/")
	out, err := cmd.Output()
	if err != nil {
		return nil
	}

	var files []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			files = append(files, line)
		}
	}
	return files
}
